<?php

namespace App\Controllers\Api\Auth;
use App\Controllers\Api\ApiBaseController;
use App\Models\OtpRecordModel;
use App\Models\CustomerModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Moment\Moment;
use Psr\Log\LoggerInterface;

class SendOtp extends ApiBaseController
{
    private $customerModel;
    private $otpRecordsModel;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->customerModel = new CustomerModel();
        $this->otpRecordsModel = new OtpRecordModel();

        $mobile_no = $this->request->getPost("mobile_no");

        $checkCustomer = $this->customerModel->where('mobile_no', $mobile_no)->first();
        if (!$checkCustomer) {
            $customerId = $this->customerModel->insert(['mobile_no'=> $mobile_no]);
        } else {
            $customerId = $checkCustomer["customer_id"];
        }

        $code = 422748;
        $expires_at = (new Moment())->addHours(1)->format("Y-m-d H:i:s");

        $this->otpRecordsModel->insert([
            "code" => $code,
            "expires_at" => $expires_at,
            "type" => 0,
            "customer_id" => $customerId
        ]);

        $data = [
            "result_code" => 200,
            "message" => "OTP sending successful",
        ];
        return $this->response->setJSON($data);

    }
}
