<?php

namespace App\Controllers\Api\v1\Auth;
use  App\Controllers\BaseController;
use App\Libraries\JWTHelper;
use App\Models\OtpRecordModel;
use App\Models\RBContactModel;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Moment\Moment;
use Psr\Log\LoggerInterface;

class VerifyOtp extends BaseController
{
    private $rbContactModel;
    private $OTPRecordsModel;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

    }

    public function index()
    {

        $this->rbContactModel = new RBContactModel();
        $this->OTPRecordsModel = new OtpRecordModel();

        $phone = $this->request->getPost("phone");
        $otp = $this->request->getPost("otp");


        $checkUser = $this->OTPRecordsModel->select(["OTPRecords.OTPRecordId", "rbcontact.*"])
            ->join("rbcontact", "rbcontact.rbcontactId=OTPRecords.rbcontactId")
            ->where("rbcontact.phone", $phone)
            ->where("OTPRecords.otp", $otp)
            ->where("OTPRecords.expiresAt > ", (new Moment())->format("Y-m-d H:i:s"))
            ->first();

        $this->OTPRecordsModel->update($checkUser["OTPRecordId"], ["expiresAt"=>"0000-00-00 00:00:00"]);


        if (!$checkUser) return $this->response->setStatusCode(401)->setJSON([
            "status"=>401,
            "message"=>"Invalid OTP or phone"
        ]);



        $jwt = JWTHelper::encode($checkUser, 10000);

        $data = [
            "status"=>200,
            "message"=>"Successfully logged in",
            "data"=>[
                "token"=>$jwt,
            ]
        ];
        return $this->response->setJSON($data);
    }
}
