<?php

namespace App\Controllers\Api\v1\Auth;
use  App\Controllers\BaseController;
use App\Libraries\JWTHelper;
use App\Models\Users;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class SignIn extends BaseController
{
    private $users;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

    }

    public function index()
    {

        $this->users = new Users();
        $username = $this->request->getPost("username");
        $password = $this->request->getPost("password");


        $checkUser = $this->users->where('username', $username)->where("password", md5($password))->first();


        if (!$checkUser) return $this->response->setStatusCode(401)->setJSON([
            "status"=>401,
            "message"=>"Username or password is invalid"
        ]);

        $jwt = JWTHelper::encode($checkUser, 10000);

        $data = [
            "status"=>200,
            "message"=>"Successfully logged in",
            "data"=>[
                "token"=>$jwt,
            ]
        ];
        return $this->response->setJSON($data);
    }
}
