<?php

namespace App\Controllers\Api\v1\Auth;
use  App\Controllers\BaseController;
use App\Models\Users;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Psr\Log\LoggerInterface;

class SignUp extends BaseController
{
    private $users;
    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

    }

    public function index()
    {
        $this->users = new Users();

        $username = $this->request->getPost("username");
        $password = $this->request->getPost("password");
        $name = $this->request->getPost("name");

        $checkUser = $this->users->where('username', $username)->first();


        if ($checkUser) return $this->response->setStatusCode(401)->setJSON([
            "status"=>401,
            "message"=>"User Already exist please login"
        ]);

        $this->users->insert([
            "name" => $name,
            "username" => $username,
            "password" => md5($password)
        ]);

        $data = [
            "status"=>200,
            "message"=>"Successful"
        ];
        return $this->response->setJSON($data);
    }
}
